# Generated by Django 6.0 on 2026-07-28 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('memory_type', models.CharField(choices=[('goal', 'Goal'), ('habit', 'Habit'), ('debt', 'Debt'), ('income', 'Income'), ('expense', 'Expense'), ('general', 'General')], default='general', max_length=20)),
                ('importance', models.IntegerField(default=5)),
                ('ebedding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
