# Generated by Django 6.0 on 2026-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memory',
            old_name='ebedding',
            new_name='embedding',
        ),
    ]
